[tasks.clean]
  enabled = false

[tasks.notarize] # required if matching task is enabled
  enabled = false
  bundle_id = "com.my-game" # the bundle ID of your came, typically in reverse domain notation
  sign_cert = "<base64-encoded certificate file>" # the base-64 encoded binary certificate file for the codesign process
  sign_cert_pwd = "<certificate password>" # the password used to protect the exported certificate
  apple_id = "<e-mail>"
  identity = "<apple developer identity UUID>"
  password = "<one-time password from Apple>"

[tasks.keystore] # required if matching task is enabled
  enabled = false
  keystore_apk = "<base64-encoded keystore file>" # the base-64 encoded binary keystore file for the APK bundles
  keystore_aab = "<base64-encoded keystore file>" # the base-64 encoded binary keystore file for the AAB bundles

[tasks.convert_images]
  enabled = false
  # extensions: a list of file extensions to convert
  # recursive: scans directories recursively if enabled, otherwise only scans the immediate directory
  # lossless: converts to lossless WebP if enabled, otherwise converts to lossy WebP
  "game/images/cg" = { extensions = ["png", "jpg"], recursive = true, lossless = true } # default values
  "game/images/bg" = { lossless = false }
  "game/images" = { } # all parameters are optional

[build] # required, at least one item must be 'true'
  pc = false  # Windows + Linux
  win = false # Windows
  linux = false # Linux
  mac = false # macOS
  web = false # Web
  steam = false # Steam
  market = false # Multiple Markets (i.e. Itch.io)
  android_apk = false # Android Universal APK
  android_aab = false # Android Play Store Bundle

[options]
  task_dir = "tasks" # optional path to a directory containing custom tasks
  clear_output_dir = false # whether to clear the output directory on startup

[renutil]
  version = "7.5.0" # the Ren'Py version to use (required)
  registry = "cache" # the directory to store installation files in
