name: Build

on: [push]

jobs:
  upload-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-linux-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: renkit
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.7
        with:
          files: '*.zip'

  build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nim and Dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y curl xz-utils g++ git mingw-w64 zip upx
          curl https://nim-lang.org/choosenim/init.sh -sSf | bash -s -- -y
          export PATH=/root/.nimble/bin:$PATH
      - name: Build Project
        run: |
          nimble build_linux_amd64
          nimble build_windows_amd64
          nimble build_windows_i386
      - name: Zip Artifacts
        run: |
          zip -j renkit-linux-amd64.zip bin/amd64/linux/*
          zip -j renkit-windows-amd64.zip bin/amd64/windows/*
          zip -j renkit-windows-i386.zip bin/i386/windows/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: renkit
          path: '*.zip'

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nim
        run: |
          brew install nim upx
      - name: Build Project
        run: |
          nimble build_macos_amd64
          nimble build_macos_arm64
      - name: Zip Artifacts
        run: |
          zip -j renkit-macos-amd64.zip bin/amd64/macos/*
          zip -j renkit-macos-arm64.zip bin/arm64/macos/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: renkit
          path: '*.zip'
